name: to-do list for demo

on: push

jobs:
  my-jobs:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     
     - name: install dependencies
       run: npm install
       
     - name: build the application
       run: npm run build
     
     - name: test the application
       run: npm test
     
     - name: check the test coverage
       run: npm test -- --coverage
     
